const quotes = [
 "Success is not final, failure is not fatal.",
"Believe you can and you're halfway there.",
"Dream big and dare to fail.",
"Your limitation—it's only your imagination.",
"Be yourself; everyone else is already taken.",
"Do what you can, with what you have, where you are.",
"To be the best, you must be able to handle the worst.",
"The only way to do great work is to love what you do.",
"Don't wait. The time will never be just right.",
"Great things never came from comfort zones.",
"Push yourself, because no one else is going to do it for you.",
"Sometimes later becomes never. Do it now.",
"Little things make big days.",
"Failure is not the opposite of success; it’s part of success.",
"You don’t have to be perfect to be amazing.",
"The harder you work for something, the greater you’ll feel when you achieve it.",
"Don’t stop when you’re tired. Stop when you’re done.",
"If you can dream it, you can do it.",
"The only limit to our realization of tomorrow is our doubts of today.",
"Keep your face always toward the sunshine—and shadows will fall behind you.",
"If opportunity doesn’t knock, build a door.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"Start where you are. Use what you have. Do what you can.",
"What you get by achieving your goals is not as important as what you become by achieving your goals.",
"Don’t watch the clock; do what it does. Keep going.",
"A winner is a dreamer who never gives up.",
"Don't be afraid to give up the good to go for the great.",
"Act as if what you do makes a difference. It does.",
"Quality is not an act, it is a habit.",
"Perseverance is not a long race; it is many short races one after the other.",
"Do not wait to strike till the iron is hot, but make it hot by striking.",
"If you’re going through hell, keep going.",
"Only those who dare to fail greatly can ever achieve greatly.",
"You are never too old to set another goal or to dream a new dream.",
"Everything you can imagine is real.",
"The secret of getting ahead is getting started.",
"What lies behind us and what lies before us are tiny matters compared to what lies within us.",
"Opportunities don't happen. You create them.",
"The future belongs to those who believe in the beauty of their dreams.",
"In the middle of every difficulty lies opportunity.",
"Your life does not get better by chance, it gets better by change.",
"Don't let yesterday take up too much of today.",
"It always seems impossible until it's done.",
"The best way to predict the future is to create it.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"Strive not to be a success, but rather to be of value.",
"If you want to achieve greatness stop asking for permission.",
"What you do today can improve all your tomorrows.",
"The key to success is to focus on goals, not obstacles.",
"Go confidently in the direction of your dreams. Live the life you have imagined.",
"It does not matter how slowly you go as long as you do not stop.",
"With the new day comes new strength and new thoughts.",
"Energy and persistence conquer all things.",
"The best time to plant a tree was 20 years ago. The second best time is now.",
"Fall seven times, stand up eight.",
"You always pass failure on the way to success.",
"Whether you think you can or you think you can't, you're right.",
"The difference between ordinary and extraordinary is that little extra.",
"Even if you’re on the right track, you’ll get run over if you just sit there.",
"Don't wish it were easier. Wish you were better.",
"If you change nothing, nothing will change.",
"Impossible is just an opinion.",
"Never give up, for that is just the place and time that the tide will turn.",
"The only person you are destined to become is the person you decide to be.",
"Courage doesn't mean you don't get afraid. Courage means you don't let fear stop you.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"If you want something you've never had, you must be willing to do something you've never done.",
"A journey of a thousand miles begins with a single step.",
"Don't limit your challenges, challenge your limits.",
"Your passion is waiting for your courage to catch up.",
"The best revenge is massive success.",
"The universe is not outside of you. Look inside yourself; everything that you want, you already are.",
"Success is not how high you have climbed, but how you make a positive difference to the world.",
"Hardships often prepare ordinary people for an extraordinary destiny.",
"Life is 10% what happens to us and 90% how we react to it.",
"It takes courage to grow up and become who you really are.",
"You are braver than you believe, stronger than you seem, and smarter than you think.",
"The mind is everything. What you think you become.",
"In any given moment we have two options: to step forward into growth or to step back into safety.",
"The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
"Act as though it is impossible to fail.",
"Do something today that your future self will thank you for.",
"Happiness is not something ready-made. It comes from your own actions.",
"You don't need to see the whole staircase, just take the first step.",
"Joy is not in things; it is in us.",
"Genius is one percent inspiration and ninety-nine percent perspiration.",
"You are enough just as you are.",
"There are no shortcuts to any place worth going.",
"If you want to lift yourself up, lift up someone else.",
"Excellence is not a skill. It is an attitude.",
"Set your goals high, and don't stop till you get there.",
"The only thing standing between you and your goal is the story you keep telling yourself.",
"Your attitude, not your aptitude, will determine your altitude.",
"The only place where success comes before work is in the dictionary.",
"A champion is defined not by their wins but by how they can recover when they fall.",
"Action is the foundational key to all success.",
"Put your heart, mind, and soul into even your smallest acts. This is the secret of success.",
"Wherever you go, go with all your heart.",
"Big journeys begin with small steps.",
"One day or day one. You decide.",
"Nothing will work unless you do.",
"Do what you feel in your heart to be right – for you’ll be criticized anyway.",
"Work hard in silence, let success be your noise.",
];

function generateQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  document.getElementById("quote").textContent = quotes[randomIndex];
}

// Optionally show a quote on page load
generateQuote();